markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
# paginate 分页
gems: [jekyll-paginate]
paginate: 6
permalink: /:year/:month/:day/:title.html

feed: /feed.xml
#这个tag用来判断book类型的博文，不展示在文章列表中，只在读后感里找到
bookTag: book
#几类标识，已读，正在读，未读,自动从markdown文章里生成书籍列表
bookTypeReaded: readed
bookTypeReading: reading
bookTypeToRead: toread
#这个tag用来判断音乐类型的博文，和book一样，都是默认不显示的
musicTag: music
#这个tag用来判断项目类型
demoTag: project
# excerpt 前期考虑用excerpt作为文章摘要,后面发出会影响统一样式，于是放弃了
#excerpt_separator: "\n\n\n\n"
#百度统计标识后期完善
baidu_analytics_id:

url: https://yexin0710.github.io
title: Yexin的个人主页
description: 整理总结自己零散的知识体系，向世界诠释自己人生的意义！
author_info: <a href="https://yexin0710.github.io/">dailc</a>
author :
  name : Tianchi Chen
  nickName : 叶心
  intro: 理胜力为常，力胜理为变；一时之强弱在力，千古之胜败在理！欢迎光临我的博客，希望你在此有所收获！
  email : 294994212@qq.com
  github : yexin0710
  githubUrl: https://github.com/yexin0710
  